name: "Contenu en inline"
multiple: false
category: 'Content'
enabled: TRUE
fields:
  imgUrl:
    type: image
    label: "image"
  pictoImg_alt:
    type: "text"
    label: "text alternative de l'image"
  title:
    type: text
    label: "Titre"
  description:
    type: text_format
    label: "Description"
    options:
      '#format': full_html
  link:
    type: url_extended
    label: "Lien"
  group_options:
    g_title: "Options"
    activeBorder:
      type: checkbox
      label: "Activer le border pour la template"
    activeBorderImage:
      type: checkbox
      label: "activer le border pour l'image"
    inversed:
      type: checkbox
      label: "inverser la template"
    colCount:
      type: select
      label: "Largeur de l'image en colonne"
      options:
        "#required": TRUE
        '#options':
          - '3': '1/4'
          - '4': '1/3'
          - '6': '1/2'



