name: "Testimonials en inline"
multiple: TRUE
category: 'Content'
enabled: TRUE
extra_fields:
  group_options:
    g_title: "Options"
    inversed:
      type: checkbox
      label: "Inversed template"
  bigTitle:
    type: text
    label: 'Big title'
  intro:
    type: textarea
    label: "Introduction"
fields:
  imageUrl:
    type: image
    label: "image"
  image_alt:
    type: "text"
    label: "text alternative de l'image"
  name:
    type: text
    label: "Nom complet"
  role:
    type: text
    label: "Rôle"
  description:
    type: text_format
    label: "Description"
    options:
      '#format': full_html



