name: 'Tabs'
multiple: FALSE
category: 'Gouvernance'
enabled: TRUE
fields:
  title:
    type: text
    label: "Titre"
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'basic_html'
  link:
    type: url_extended
    label: 'Lien'
