#schema for the configuration file of RSVPList module
vactory_icon.settings:
  type: config_object
  label: 'vactory icon Settings'
#  mapping:
#    allowed_types:
#      type: sequence
#      label: 'Content types RSVP form can display on'
#      sequence:
#        type: string
#        label: 'Content type'