vactory_keycloak.settings:
  type: config_object
  label: 'Social Auth Keycloak settings'
  mapping:
    app_server_url:
      type: string
      label: 'Application Server URL'
    app_realm:
      type: string
      label: 'App Realm'
    app_client_id:
      type: string
      label: 'Client ID'
    app_client_secret:
      type: string
      label: 'Client Secret'
    scopes:
      type: string
      label: 'Scopes to be requested'
    redirect_uri:
      type: string
      label: 'Redirect URI'
