name: 'List'
multiple: FALSE
category: 'News'
enabled: TRUE
fields:
  views:
    type: dynamic_views
    label: 'Views'
    options:
      '#required': TRUE
      '#default_value':
        views_id: vactory_news
        views_display_id: block_list
        fields:
          id: id
          uuid: key
          title: title
          url: url
          field_vactory_excerpt: excerpt
          field_vactory_taxonomy_1: category
          field_vactory_media_image: image
        vocabularies:
          vactory_news_theme: vactory_news_theme
