name: 'Simple'
multiple: FALSE
category: 'Formulaires'
enabled: TRUE
fields:
  webform_id:
    type: webform_decoupled
    label: 'Formulaire'
    options:
      '#required': TRUE
  style:
    type: textarea
    label: "Style"
    options:
      '#description': 'Objet JSON pour theming.'
extra_fields:
  title:
    type: text
    label: "Titre"
  intro:
    type: text_format
    label: 'Introduction'
    options:
      '#format': 'full_html'
  link:
    type: url_extended
    label: 'Lien'
